# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ryoichi Izumita

"""Simple multi-target scaffold generation for fsl-domain."""
from __future__ import annotations

from typing import Dict, List

from ..domain_ir import DomainSpec


def generate_simple_target(domain: DomainSpec, target: str) -> Dict[str, str]:
    if target == "python":
        return {"domain_scaffold.py": _python(domain)}
    if target == "kotlin":
        return {"DomainScaffold.kt": _kotlin(domain)}
    if target == "swift":
        return {"DomainScaffold.swift": _swift(domain)}
    if target == "rust":
        return {"domain_scaffold.rs": _rust(domain)}
    raise ValueError(f"unsupported domain generation target: {target}")


def _python(domain: DomainSpec) -> str:
    lines: List[str] = [
        "# Auto-generated by fslc domain generate. Treat as scaffold.",
        "from dataclasses import dataclass",
        "from typing import Any",
        "",
    ]
    for aggregate in domain.aggregates:
        lines.extend([
            f"@dataclass(frozen=True)",
            f"class {aggregate.name}State:",
            *[f"    {field.name}: Any" for field in aggregate.state],
            "",
            f"def decide_{_snake(aggregate.name)}(state: {aggregate.name}State, command: dict) -> list[dict]:",
            "    match command.get('type'):",
        ])
        for command in aggregate.commands:
            decide = aggregate.decide_map().get(command.name)
            emitted = list(decide.emits) if decide else []
            lines.extend([
                f"        case '{command.name}':",
                *[f"            # requires {req}" for req in (decide.requires if decide else ())],
                *[f"            # rejects {rej.error} when {rej.condition}" for rej in (decide.rejects if decide else ())],
                "            return [" + ", ".join(f"{{'type': '{event}'}}" for event in emitted) + "]",
            ])
        lines.extend([
            "        case _:",
            "            raise ValueError(f\"unknown command: {command.get('type')}\")",
            "",
            f"def evolve_{_snake(aggregate.name)}(state: {aggregate.name}State, event: dict) -> {aggregate.name}State:",
            "    # Fill assignment details from the FSL evolve blocks before production use.",
            "    return state",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _kotlin(domain: DomainSpec) -> str:
    lines = ["// Auto-generated by fslc domain generate. Treat as scaffold.", ""]
    for aggregate in domain.aggregates:
        fields = ", ".join(f"val {field.name}: Any" for field in aggregate.state)
        lines.extend([
            f"data class {aggregate.name}State({fields})",
            f"sealed interface {aggregate.name}Command",
            f"sealed interface {aggregate.name}Event",
            f"sealed interface {aggregate.name}Error",
            "",
            f"fun decide{aggregate.name}(state: {aggregate.name}State, command: {aggregate.name}Command): List<{aggregate.name}Event> =",
            "    when (command) {",
            "        else -> emptyList()",
            "    }",
            "",
            f"fun evolve{aggregate.name}(state: {aggregate.name}State, event: {aggregate.name}Event): {aggregate.name}State = state",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _swift(domain: DomainSpec) -> str:
    lines = ["// Auto-generated by fslc domain generate. Treat as scaffold.", ""]
    for aggregate in domain.aggregates:
        lines.extend([
            f"struct {aggregate.name}State {{",
            *[f"    var {field.name}: Any" for field in aggregate.state],
            "}",
            f"enum {aggregate.name}Command {{",
            *[f"    case {command.name[:1].lower() + command.name[1:]}" for command in aggregate.commands],
            "}",
            f"enum {aggregate.name}Event {{",
            *[f"    case {event.name[:1].lower() + event.name[1:]}" for event in aggregate.events],
            "}",
            "",
            f"func decide{aggregate.name}(state: {aggregate.name}State, command: {aggregate.name}Command) -> [{aggregate.name}Event] {{",
            "    return []",
            "}",
            "",
            f"func evolve{aggregate.name}(state: {aggregate.name}State, event: {aggregate.name}Event) -> {aggregate.name}State {{",
            "    return state",
            "}",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _rust(domain: DomainSpec) -> str:
    lines = ["// Auto-generated by fslc domain generate. Treat as scaffold.", ""]
    for aggregate in domain.aggregates:
        lines.extend([
            f"pub struct {aggregate.name}State {{",
            *[f"    pub {field.name}: (), " for field in aggregate.state],
            "}",
            f"pub enum {aggregate.name}Command {{",
            *[f"    {command.name}," for command in aggregate.commands],
            "}",
            f"pub enum {aggregate.name}Event {{",
            *[f"    {event.name}," for event in aggregate.events],
            "}",
            f"pub fn decide_{_snake(aggregate.name)}(_state: &{aggregate.name}State, _command: {aggregate.name}Command) -> Vec<{aggregate.name}Event> {{",
            "    Vec::new()",
            "}",
            f"pub fn evolve_{_snake(aggregate.name)}(state: {aggregate.name}State, _event: {aggregate.name}Event) -> {aggregate.name}State {{",
            "    state",
            "}",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _snake(name: str) -> str:
    out = []
    for index, ch in enumerate(name):
        if index and ch.isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)
