# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ryoichi Izumita

"""TypeScript Functional DDD scaffold generation for fsl-domain."""
from __future__ import annotations

import re
from typing import Dict, List

from ..domain_ir import DomainAggregate, DomainAssignment, DomainEvent, DomainField, DomainSpec


def _safe(name):
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not out:
        out = "x"
    if out[0].isdigit():
        out = "_" + out
    return out


def _camel(name):
    parts = _safe(name).split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def _type_name(raw):
    if raw == "Int":
        return "number"
    if raw == "Bool":
        return "boolean"
    if raw.startswith("Option<") and raw.endswith(">"):
        inner = _type_name(raw[len("Option<"):-1].strip())
        return f"{inner} | null"
    return raw


def _field_line(field: DomainField):
    return f"  {_camel(field.name)}: {_type_name(field.type_name)}"


def _event_payload(event: DomainEvent):
    fields = [f"{_camel(field.name)}: {_camel(field.name)}" for field in event.fields]
    return "{ " + ", ".join([f'type: "{event.name}"'] + fields) + " }"


def generate_typescript(domain: DomainSpec) -> Dict[str, str]:
    files = {}
    files["types.ts"] = _emit_types(domain)
    for aggregate in domain.aggregates:
        prefix = _module_name(aggregate.name)
        files[f"{prefix}/decide.ts"] = _emit_decide(aggregate)
        files[f"{prefix}/evolve.ts"] = _emit_evolve(aggregate)
        files[f"{prefix}/adapter.ts"] = _emit_adapter(aggregate)
    if domain.effects:
        files["effects.ts"] = _emit_effects(domain)
    if domain.sagas:
        files["process-manager.ts"] = _emit_process_manager(domain)
    return files


def _module_name(name):
    camel = _camel(name)
    return camel[:1].lower() + camel[1:]


def _emit_types(domain: DomainSpec):
    lines: List[str] = [
        "// Auto-generated by fslc domain generate. Treat as scaffold.",
        "",
        "export type Ok<T> = { ok: true; value: T }",
        "export type Err<E> = { ok: false; error: E }",
        "export type Result<T, E> = Ok<T> | Err<E>",
        "export const ok = <T>(value: T): Ok<T> => ({ ok: true, value })",
        "export const err = <E>(error: E): Err<E> => ({ ok: false, error })",
        "",
    ]
    for ty in domain.types:
        if ty.kind == "enum":
            members = " | ".join(f'"{member}"' for member in ty.members)
            lines.append(f"export type {ty.name} = {members}")
        elif ty.kind == "range":
            lines.append(f"export type {ty.name} = number")
        elif ty.kind == "value_object":
            lines.append(f"export type {ty.name} = {{")
            lines.extend(_field_line(field) for field in ty.fields)
            lines.append("}")
        lines.append("")
    for aggregate in domain.aggregates:
        for ref in _external_refs(aggregate):
            if ref not in {ty.name for ty in domain.types} and ref not in {"Int", "Bool"}:
                lines.append(f"export type {ref} = number")
        lines.append("")
        lines.append(f"export type {aggregate.name}State = {{")
        lines.extend(_field_line(field) for field in aggregate.state)
        lines.append("}")
        lines.append("")
        lines.append(f"export type {aggregate.name}Command =")
        if aggregate.commands:
            for command in aggregate.commands:
                payload = [f'type: "{command.name}"']
                payload.extend(f"{_camel(field.name)}: {_type_name(field.type_name)}" for field in command.inputs)
                lines.append("  | { " + "; ".join(payload) + " }")
        else:
            lines.append("  never")
        lines.append("")
        lines.append(f"export type {aggregate.name}Event =")
        if aggregate.events:
            for event in aggregate.events:
                payload = [f'type: "{event.name}"']
                payload.extend(f"{_camel(field.name)}: {_type_name(field.type_name)}" for field in event.fields)
                lines.append("  | { " + "; ".join(payload) + " }")
        else:
            lines.append("  never")
        lines.append("")
        lines.append(f"export type {aggregate.name}Error =")
        if aggregate.errors:
            for error in aggregate.errors:
                lines.append(f'  | {{ type: "{error.name}" }}')
        else:
            lines.append("  never")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _external_refs(aggregate: DomainAggregate):
    refs = set()
    if aggregate.id_type:
        refs.add(aggregate.id_type)
    for field in aggregate.state:
        refs.update(_type_refs(field.type_name))
    for command in aggregate.commands:
        for field in command.inputs:
            refs.update(_type_refs(field.type_name))
    for event in aggregate.events:
        for field in event.fields:
            refs.update(_type_refs(field.type_name))
    return refs


def _type_refs(raw):
    return {
        name for name in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", raw)
        if name not in {"Int", "Bool", "Map", "Set", "Seq", "Option"}
    }


def _emit_decide(aggregate: DomainAggregate):
    lines = [
        "// Auto-generated by fslc domain generate. Fill policy gaps before production use.",
        f"import {{ err, ok, type Result, type {aggregate.name}Command, type {aggregate.name}Error, type {aggregate.name}Event, type {aggregate.name}State }} from '../types'",
        "",
        f"export function decide{aggregate.name}(",
        f"  state: {aggregate.name}State,",
        f"  command: {aggregate.name}Command",
        f"): Result<{aggregate.name}Event[], {aggregate.name}Error> {{",
        "  switch (command.type) {",
    ]
    decides = aggregate.decide_map()
    for command in aggregate.commands:
        decide = decides.get(command.name)
        lines.append(f'    case "{command.name}": {{')
        if decide is None:
            lines.append(f'      return err({{ type: "Unhandled{command.name}" }} as {aggregate.name}Error)')
            lines.append("    }")
            continue
        for reject in decide.rejects:
            lines.append(f"      // rejects {reject.error} when {reject.condition}")
        for req in decide.requires:
            lines.append(f"      // requires {req}")
        events = []
        for event_name in decide.emits:
            event = aggregate.event_map().get(event_name)
            if event:
                events.append(_event_construct(event))
            else:
                events.append(f'{{ type: "{event_name}" }} as {aggregate.name}Event')
        lines.append(f"      return ok([{', '.join(events)}])")
        lines.append("    }")
    lines.extend([
        "    default:",
        "      return err({ type: 'UnknownCommand' } as unknown as " + aggregate.name + "Error)",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def _event_construct(event: DomainEvent):
    fields = []
    for field in event.fields:
        name = _camel(field.name)
        fields.append(f"{name}: (command as any).{name}")
    return "{ " + ", ".join([f'type: "{event.name}"'] + fields) + " }"


def _emit_evolve(aggregate: DomainAggregate):
    lines = [
        "// Auto-generated by fslc domain generate. Keep pure: no I/O, clocks, repositories, or network calls.",
        f"import {{ type {aggregate.name}Event, type {aggregate.name}State }} from '../types'",
        "",
        f"export function evolve{aggregate.name}(state: {aggregate.name}State, event: {aggregate.name}Event): {aggregate.name}State {{",
        "  switch (event.type) {",
    ]
    evolves = aggregate.evolve_map()
    for event in aggregate.events:
        evolve = evolves.get(event.name)
        lines.append(f'    case "{event.name}":')
        if evolve is None or not evolve.assignments:
            lines.append("      return state")
            continue
        fields = []
        comments = []
        for assignment in evolve.assignments:
            rendered = _render_ts_assignment(assignment)
            if rendered:
                fields.append(rendered)
            else:
                comments.append(f"      // {assignment.target} = {assignment.expr}")
        lines.extend(comments)
        lines.append("      return { ...state, " + ", ".join(fields) + " }")
    lines.extend([
        "    default:",
        "      return state",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def _render_ts_assignment(assignment: DomainAssignment):
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", assignment.target):
        return None
    expr = assignment.expr.strip()
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", expr):
        expr = f'"{expr}"'
    return f"{_camel(assignment.target)}: {expr}"


def _emit_adapter(aggregate: DomainAggregate):
    name = aggregate.name
    return "\n".join([
        "// Auto-generated by fslc domain generate. Wire this adapter to fslc testgen output.",
        f"import {{ decide{name} }} from './decide'",
        f"import {{ evolve{name} }} from './evolve'",
        f"import {{ type {name}Command, type {name}State }} from '../types'",
        "",
        f"export class {name}FslAdapter {{",
        f"  private state: {name}State",
        "",
        f"  constructor(initialState: {name}State) {{",
        "    this.state = initialState",
        "  }",
        "",
        f"  reset(initialState: {name}State): void {{",
        "    this.state = initialState",
        "  }",
        "",
        "  step(action: string, params: Record<string, unknown>) {",
        "    const command = mapFslActionToCommand(action, params)",
        f"    const result = decide{name}(this.state, command)",
        "    if (result.ok) {",
        f"      this.state = result.value.reduce((s, e) => evolve{name}(s, e), this.state)",
        "    }",
        "    return result",
        "  }",
        "",
        "  observe() {",
        "    return { ...this.state }",
        "  }",
        "}",
        "",
        f"export function mapFslActionToCommand(action: string, params: Record<string, unknown>): {name}Command {{",
        "  switch (action) {",
        *[
            f'    case "{_action_name(name)}_{_action_name(command.name)}":\n'
            f'      return {{ type: "{command.name}", ...(params as any) }} as {name}Command'
            for command in aggregate.commands
        ],
        "    default:",
        "      throw new Error(`Unknown FSL action: ${action}`)",
        "  }",
        "}",
        "",
    ])


def _action_name(name):
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    return s.lower()


def _emit_effects(domain: DomainSpec):
    lines = [
        "// Auto-generated by fslc domain generate. Effect handlers are outside the pure domain core.",
        "import type { " + ", ".join(f"{agg.name}Event" for agg in domain.aggregates) + " } from './types'",
        "",
    ]
    for effect in domain.effects:
        outcomes = " | ".join(_event_type_for(domain, event) for event in effect.outcomes) or "never"
        request = effect.handles or effect.request_event or "unknown"
        lines.extend([
            f"export interface {effect.name}Handler {{",
            f"  handle(event: Extract<{_all_event_union(domain)}, {{ type: \"{request}\" }}>): Promise<{outcomes}>",
            "}",
            "",
        ])
    return "\n".join(lines)


def _emit_process_manager(domain: DomainSpec):
    lines = [
        "// Auto-generated by fslc domain generate. Process managers coordinate events; keep side effects in handlers.",
        "import type { " + ", ".join(f"{agg.name}Event" for agg in domain.aggregates) + " } from './types'",
        "",
        f"type DomainEvent = {_all_event_union(domain)}",
        "type ProcessAction = { type: string; event: DomainEvent }",
        "",
    ]
    for saga in domain.sagas:
        lines.extend([
            f"export function on{saga.name}(event: DomainEvent): ProcessAction[] {{",
            "  switch (event.type) {",
        ])
        if saga.starts_on:
            emitted = _saga_initial_emits(saga)
            lines.append(f'    case "{saga.starts_on}":')
            if emitted:
                actions = ", ".join(
                    "{ type: \"emit\", event: " + _event_placeholder(domain, event) + " }"
                    for event in emitted
                )
                lines.append(f"      return [{actions}]")
            else:
                lines.append("      return []")
        for compensation in saga.compensations:
            lines.append(f'    case "{compensation.trigger_event}":')
            if compensation.emits:
                actions = ", ".join(
                    "{ type: \"emit\", event: " + _event_placeholder(domain, event) + " }"
                    for event in compensation.emits
                )
                lines.append(f"      // after {compensation.after_event}")
                lines.append(f"      return [{actions}]")
            else:
                lines.append("      return []")
        lines.extend([
            "    default:",
            "      return []",
            "  }",
            "}",
            "",
        ])
    return "\n".join(lines)


def _saga_initial_emits(saga):
    if not saga.steps:
        return []
    return list(saga.steps[0].emits)


def _event_placeholder(domain: DomainSpec, event_name: str):
    event = None
    owner = None
    for aggregate in domain.aggregates:
        event = aggregate.event_map().get(event_name)
        if event:
            owner = aggregate
            break
    if event is None or owner is None:
        return f'{{ type: "{event_name}" }} as DomainEvent'
    fields = [f"{_camel(field.name)}: undefined as unknown as {_type_name(field.type_name)}" for field in event.fields]
    return "{ " + ", ".join([f'type: "{event.name}"'] + fields) + f" }} as {owner.name}Event"


def _all_event_union(domain: DomainSpec):
    return " | ".join(f"{agg.name}Event" for agg in domain.aggregates) or "never"


def _event_type_for(domain: DomainSpec, event_name: str):
    for aggregate in domain.aggregates:
        if event_name in aggregate.event_map():
            return f'Extract<{aggregate.name}Event, {{ type: "{event_name}" }}>'
    return "never"
