// SPDX-License-Identifier: Apache-2.0

//! Generate the table of skill files the binary carries.
//!
//! The Agent Skills travel inside the binary, so an install needs no second
//! download and cannot drift from the `fslc` that carries it.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn collect_files(path: &Path, files: &mut Vec<PathBuf>) {
    let kind = std::fs::symlink_metadata(path)
        .unwrap_or_else(|error| panic!("failed to inspect {}: {error}", path.display()))
        .file_type();
    // Refuse rather than follow. Embedding a link means embedding whatever it
    // aims at, without saying so, and a loop never finishes walking.
    assert!(
        !kind.is_symlink(),
        "{} is a symbolic link; the embedded payload must be plain files",
        path.display()
    );
    if kind.is_file() {
        files.push(path.to_path_buf());
        return;
    }
    let mut entries = std::fs::read_dir(path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()))
        .map(|entry| entry.expect("read skill entry").path())
        .collect::<Vec<_>>();
    entries.sort();
    for entry in entries {
        collect_files(&entry, files);
    }
}

/// Every directory under `skills/` is a skill. A file sitting directly under
/// `skills/`, such as its README, is not one.
fn collect_skill_files(root: &Path) -> Vec<(String, PathBuf)> {
    let mut skills = std::fs::read_dir(root)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", root.display()))
        .map(|entry| entry.expect("read skills entry").path())
        .filter(|path| path.is_dir())
        .collect::<Vec<_>>();
    skills.sort();
    let mut embedded = Vec::new();
    for skill in skills {
        let mut files = Vec::new();
        collect_files(&skill, &mut files);
        for file in files {
            let relative = file
                .strip_prefix(root)
                .expect("skills-relative path")
                .to_string_lossy()
                .replace('\\', "/");
            embedded.push((relative, file));
        }
    }
    // Ordered by relative path, so `fsl-business/...` precedes `fsl/...`.
    // Each skill's files stay contiguous, which is what the accessors rely on.
    embedded.sort();
    embedded
}

fn main() {
    let manifest = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let workspace = manifest.parent().expect("Rust workspace root");
    let skills_root = workspace.parent().expect("repository root").join("skills");
    println!("cargo:rerun-if-changed={}", skills_root.display());
    let skill_files = collect_skill_files(&skills_root);
    assert!(
        !skill_files.is_empty(),
        "no skill directory found under {}",
        skills_root.display()
    );
    let mut generated = String::from(
        "// @generated by build.rs from the repository's skills/ directory.\n\
         pub static EMBEDDED_SKILL_FILES: &[(&str, &str)] = &[\n",
    );
    for (relative, file) in &skill_files {
        println!("cargo:rerun-if-changed={}", file.display());
        writeln!(
            generated,
            "    ({:?}, include_str!({:?})),",
            relative,
            file.to_str().expect("UTF-8 skill path")
        )
        .expect("write generated skill entry");
    }
    generated.push_str("];\n");
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out_dir.join("embedded_skills.rs"), generated)
        .expect("write embedded_skills.rs");
}
