// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Ryoichi Izumita

//! Native multi-target generators for the fsl-domain frontend.

use fsl_syntax::{
    DomainAggregate, DomainAssignment, DomainEvent, DomainField, DomainSaga, DomainSpec,
};
use std::collections::{BTreeMap, BTreeSet};

pub(crate) fn generate(
    domain: &DomainSpec,
    target: &str,
) -> Result<BTreeMap<String, String>, String> {
    match target {
        "typescript" => Ok(generate_typescript(domain)),
        "python" => Ok(BTreeMap::from([(
            "domain_scaffold.py".to_owned(),
            generate_python(domain),
        )])),
        "kotlin" => Ok(BTreeMap::from([(
            "DomainScaffold.kt".to_owned(),
            generate_kotlin(domain),
        )])),
        "swift" => Ok(BTreeMap::from([(
            "DomainScaffold.swift".to_owned(),
            generate_swift(domain),
        )])),
        "rust" => Ok(BTreeMap::from([(
            "domain_scaffold.rs".to_owned(),
            generate_rust(domain),
        )])),
        _ => Err(format!("unsupported domain generation target: {target}")),
    }
}

fn snake(name: &str) -> String {
    let mut output = String::new();
    for (index, character) in name.chars().enumerate() {
        if index > 0 && character.is_ascii_uppercase() {
            output.push('_');
        }
        output.push(character.to_ascii_lowercase());
    }
    output
}

fn generate_python(domain: &DomainSpec) -> String {
    let mut lines = vec![
        "# Auto-generated by fslc domain generate. Treat as scaffold.".to_owned(),
        "from dataclasses import dataclass".to_owned(),
        "from typing import Any".to_owned(),
        String::new(),
    ];
    for aggregate in &domain.aggregates {
        lines.push("@dataclass(frozen=True)".to_owned());
        lines.push(format!("class {}State:", aggregate.name));
        lines.extend(
            aggregate
                .state
                .iter()
                .map(|field| format!("    {}: Any", field.name)),
        );
        lines.push(String::new());
        lines.push(format!(
            "def decide_{}(state: {}State, command: dict) -> list[dict]:",
            snake(&aggregate.name),
            aggregate.name
        ));
        lines.push("    match command.get('type'):".to_owned());
        for command in &aggregate.commands {
            let decision = aggregate
                .decides
                .iter()
                .find(|decision| decision.command == command.name);
            lines.push(format!("        case '{}':", command.name));
            if let Some(decision) = decision {
                lines.extend(
                    decision
                        .requires
                        .iter()
                        .map(|requirement| format!("            # requires {requirement}")),
                );
                lines.extend(decision.rejects.iter().map(|rejection| {
                    format!(
                        "            # rejects {} when {}",
                        rejection.error, rejection.condition
                    )
                }));
                let events = decision
                    .emits
                    .iter()
                    .map(|event| format!("{{'type': '{event}'}}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!("            return [{events}]"));
            } else {
                lines.push("            return []".to_owned());
            }
        }
        lines.extend([
            "        case _:".to_owned(),
            "            raise ValueError(f\"unknown command: {command.get('type')}\")".to_owned(),
            String::new(),
            format!(
                "def evolve_{}(state: {}State, event: dict) -> {}State:",
                snake(&aggregate.name),
                aggregate.name,
                aggregate.name
            ),
            "    # Fill assignment details from the FSL evolve blocks before production use."
                .to_owned(),
            "    return state".to_owned(),
            String::new(),
        ]);
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn generate_kotlin(domain: &DomainSpec) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Treat as scaffold.".to_owned(),
        String::new(),
    ];
    for aggregate in &domain.aggregates {
        let fields = aggregate
            .state
            .iter()
            .map(|field| format!("val {}: Any", field.name))
            .collect::<Vec<_>>()
            .join(", ");
        lines.extend([
            format!("data class {}State({fields})", aggregate.name),
            format!("sealed interface {}Command", aggregate.name),
            format!("sealed interface {}Event", aggregate.name),
            format!("sealed interface {}Error", aggregate.name),
            String::new(),
            format!(
                "fun decide{}(state: {}State, command: {}Command): List<{}Event> =",
                aggregate.name, aggregate.name, aggregate.name, aggregate.name
            ),
            "    when (command) {".to_owned(),
            "        else -> emptyList()".to_owned(),
            "    }".to_owned(),
            String::new(),
            format!(
                "fun evolve{}(state: {}State, event: {}Event): {}State = state",
                aggregate.name, aggregate.name, aggregate.name, aggregate.name
            ),
            String::new(),
        ]);
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    chars.next().map_or_else(String::new, |first| {
        first.to_ascii_lowercase().to_string() + chars.as_str()
    })
}

fn generate_swift(domain: &DomainSpec) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Treat as scaffold.".to_owned(),
        String::new(),
    ];
    for aggregate in &domain.aggregates {
        lines.push(format!("struct {}State {{", aggregate.name));
        lines.extend(
            aggregate
                .state
                .iter()
                .map(|field| format!("    var {}: Any", field.name)),
        );
        lines.push("}".to_owned());
        lines.push(format!("enum {}Command {{", aggregate.name));
        lines.extend(
            aggregate
                .commands
                .iter()
                .map(|command| format!("    case {}", lower_first(&command.name))),
        );
        lines.push("}".to_owned());
        lines.push(format!("enum {}Event {{", aggregate.name));
        lines.extend(
            aggregate
                .events
                .iter()
                .map(|event| format!("    case {}", lower_first(&event.name))),
        );
        lines.extend([
            "}".to_owned(),
            String::new(),
            format!(
                "func decide{}(state: {}State, command: {}Command) -> [{}Event] {{",
                aggregate.name, aggregate.name, aggregate.name, aggregate.name
            ),
            "    return []".to_owned(),
            "}".to_owned(),
            String::new(),
            format!(
                "func evolve{}(state: {}State, event: {}Event) -> {}State {{",
                aggregate.name, aggregate.name, aggregate.name, aggregate.name
            ),
            "    return state".to_owned(),
            "}".to_owned(),
            String::new(),
        ]);
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn generate_rust(domain: &DomainSpec) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Treat as scaffold.".to_owned(),
        String::new(),
    ];
    for aggregate in &domain.aggregates {
        lines.push(format!("pub struct {}State {{", aggregate.name));
        lines.extend(
            aggregate
                .state
                .iter()
                .map(|field| format!("    pub {}: (), ", field.name)),
        );
        lines.push("}".to_owned());
        lines.push(format!("pub enum {}Command {{", aggregate.name));
        lines.extend(
            aggregate
                .commands
                .iter()
                .map(|command| format!("    {},", command.name)),
        );
        lines.push("}".to_owned());
        lines.push(format!("pub enum {}Event {{", aggregate.name));
        lines.extend(
            aggregate
                .events
                .iter()
                .map(|event| format!("    {},", event.name)),
        );
        lines.extend([
            "}".to_owned(),
            format!(
                "pub fn decide_{}(_state: &{}State, _command: {}Command) -> Vec<{}Event> {{",
                snake(&aggregate.name),
                aggregate.name,
                aggregate.name,
                aggregate.name
            ),
            "    Vec::new()".to_owned(),
            "}".to_owned(),
            format!(
                "pub fn evolve_{}(state: {}State, _event: {}Event) -> {}State {{",
                snake(&aggregate.name),
                aggregate.name,
                aggregate.name,
                aggregate.name
            ),
            "    state".to_owned(),
            "}".to_owned(),
            String::new(),
        ]);
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn safe(name: &str) -> String {
    let mut output = name
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    if output.is_empty() {
        output.push('x');
    }
    if output.starts_with(|character: char| character.is_ascii_digit()) {
        output.insert(0, '_');
    }
    output
}

fn camel(name: &str) -> String {
    let safe = safe(name);
    let mut parts = safe.split('_');
    let mut output = parts.next().unwrap_or_default().to_owned();
    for part in parts {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            output.push(first.to_ascii_uppercase());
            output.push_str(chars.as_str());
        }
    }
    output
}

fn module_name(name: &str) -> String {
    lower_first(&camel(name))
}

fn type_name(raw: &str) -> String {
    if raw == "Int" {
        return "number".to_owned();
    }
    if raw == "Bool" {
        return "boolean".to_owned();
    }
    if let Some(inner) = raw
        .strip_prefix("Option<")
        .and_then(|value| value.strip_suffix('>'))
    {
        return format!("{} | null", type_name(inner.trim()));
    }
    raw.to_owned()
}

fn field_line(field: &DomainField) -> String {
    format!("  {}: {}", camel(&field.name), type_name(&field.type_name))
}

fn type_references(raw: &str) -> BTreeSet<String> {
    raw.split(|character: char| !(character.is_ascii_alphanumeric() || character == '_'))
        .filter(|part| {
            !part.is_empty()
                && part
                    .chars()
                    .next()
                    .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
                && !matches!(*part, "Int" | "Bool" | "Map" | "Set" | "Seq" | "Option")
        })
        .map(str::to_owned)
        .collect()
}

fn external_references(aggregate: &DomainAggregate) -> BTreeSet<String> {
    let mut references = BTreeSet::new();
    if let Some(id_type) = &aggregate.id_type {
        references.insert(id_type.clone());
    }
    for field in aggregate
        .state
        .iter()
        .chain(
            aggregate
                .commands
                .iter()
                .flat_map(|command| &command.inputs),
        )
        .chain(aggregate.events.iter().flat_map(|event| &event.fields))
    {
        references.extend(type_references(&field.type_name));
    }
    references
}

fn generate_typescript(domain: &DomainSpec) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    files.insert("types.ts".to_owned(), emit_types(domain));
    for aggregate in &domain.aggregates {
        let prefix = module_name(&aggregate.name);
        files.insert(format!("{prefix}/decide.ts"), emit_decide(aggregate));
        files.insert(format!("{prefix}/evolve.ts"), emit_evolve(aggregate));
        files.insert(format!("{prefix}/adapter.ts"), emit_adapter(aggregate));
    }
    if !domain.effects.is_empty() {
        files.insert("effects.ts".to_owned(), emit_effects(domain));
    }
    if !domain.sagas.is_empty() {
        files.insert(
            "process-manager.ts".to_owned(),
            emit_process_manager(domain),
        );
    }
    files
}

fn emit_types(domain: &DomainSpec) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Treat as scaffold.".to_owned(),
        String::new(),
        "export type Ok<T> = { ok: true; value: T }".to_owned(),
        "export type Err<E> = { ok: false; error: E }".to_owned(),
        "export type Result<T, E> = Ok<T> | Err<E>".to_owned(),
        "export const ok = <T>(value: T): Ok<T> => ({ ok: true, value })".to_owned(),
        "export const err = <E>(error: E): Err<E> => ({ ok: false, error })".to_owned(),
        String::new(),
    ];
    for ty in &domain.types {
        match ty.kind.as_str() {
            "enum" => lines.push(format!(
                "export type {} = {}",
                ty.name,
                ty.members
                    .iter()
                    .map(|member| format!("\"{member}\""))
                    .collect::<Vec<_>>()
                    .join(" | ")
            )),
            "range" => lines.push(format!("export type {} = number", ty.name)),
            "value_object" => {
                lines.push(format!("export type {} = {{", ty.name));
                lines.extend(ty.fields.iter().map(field_line));
                lines.push("}".to_owned());
            }
            _ => {}
        }
        lines.push(String::new());
    }
    let declared = domain
        .types
        .iter()
        .map(|ty| ty.name.as_str())
        .collect::<BTreeSet<_>>();
    for aggregate in &domain.aggregates {
        for reference in external_references(aggregate) {
            if !declared.contains(reference.as_str())
                && !matches!(reference.as_str(), "Int" | "Bool")
            {
                lines.push(format!("export type {reference} = number"));
            }
        }
        lines.push(String::new());
        lines.push(format!("export type {}State = {{", aggregate.name));
        lines.extend(aggregate.state.iter().map(field_line));
        lines.extend(["}".to_owned(), String::new()]);
        lines.push(format!("export type {}Command =", aggregate.name));
        if aggregate.commands.is_empty() {
            lines.push("  never".to_owned());
        } else {
            for command in &aggregate.commands {
                let mut payload = vec![format!("type: \"{}\"", command.name)];
                payload.extend(command.inputs.iter().map(|field| {
                    format!("{}: {}", camel(&field.name), type_name(&field.type_name))
                }));
                lines.push(format!("  | {{ {} }}", payload.join("; ")));
            }
        }
        lines.push(String::new());
        lines.push(format!("export type {}Event =", aggregate.name));
        if aggregate.events.is_empty() {
            lines.push("  never".to_owned());
        } else {
            for event in &aggregate.events {
                let mut payload = vec![format!("type: \"{}\"", event.name)];
                payload.extend(event.fields.iter().map(|field| {
                    format!("{}: {}", camel(&field.name), type_name(&field.type_name))
                }));
                lines.push(format!("  | {{ {} }}", payload.join("; ")));
            }
        }
        lines.push(String::new());
        lines.push(format!("export type {}Error =", aggregate.name));
        if aggregate.errors.is_empty() {
            lines.push("  never".to_owned());
        } else {
            lines.extend(
                aggregate
                    .errors
                    .iter()
                    .map(|error| format!("  | {{ type: \"{}\" }}", error.name)),
            );
        }
        lines.push(String::new());
    }
    format!("{}\n", lines.join("\n").trim_end())
}

fn event_construct(event: &DomainEvent, aggregate: &DomainAggregate) -> String {
    let mut fields = vec![format!("type: \"{}\"", event.name)];
    fields.extend(event.fields.iter().map(|field| {
        let name = camel(&field.name);
        format!("{name}: (command as any).{name}")
    }));
    if fields.is_empty() {
        format!("{{ type: \"{}\" }} as {}Event", event.name, aggregate.name)
    } else {
        format!("{{ {} }}", fields.join(", "))
    }
}

fn emit_decide(aggregate: &DomainAggregate) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Fill policy gaps before production use."
            .to_owned(),
        format!(
            "import {{ err, ok, type Result, type {}Command, type {}Error, type {}Event, type {}State }} from '../types'",
            aggregate.name, aggregate.name, aggregate.name, aggregate.name
        ),
        String::new(),
        format!("export function decide{}(", aggregate.name),
        format!("  state: {}State,", aggregate.name),
        format!("  command: {}Command", aggregate.name),
        format!(
            "): Result<{}Event[], {}Error> {{",
            aggregate.name, aggregate.name
        ),
        "  switch (command.type) {".to_owned(),
    ];
    for command in &aggregate.commands {
        let decision = aggregate
            .decides
            .iter()
            .find(|decision| decision.command == command.name);
        lines.push(format!("    case \"{}\": {{", command.name));
        let Some(decision) = decision else {
            lines.extend([
                format!(
                    "      return err({{ type: \"Unhandled{}\" }} as {}Error)",
                    command.name, aggregate.name
                ),
                "    }".to_owned(),
            ]);
            continue;
        };
        lines.extend(decision.rejects.iter().map(|rejection| {
            format!(
                "      // rejects {} when {}",
                rejection.error, rejection.condition
            )
        }));
        lines.extend(
            decision
                .requires
                .iter()
                .map(|requirement| format!("      // requires {requirement}")),
        );
        let events = decision
            .emits
            .iter()
            .map(|event_name| {
                aggregate
                    .events
                    .iter()
                    .find(|event| event.name == *event_name)
                    .map_or_else(
                        || format!("{{ type: \"{event_name}\" }} as {}Event", aggregate.name),
                        |event| event_construct(event, aggregate),
                    )
            })
            .collect::<Vec<_>>()
            .join(", ");
        lines.extend([format!("      return ok([{events}])"), "    }".to_owned()]);
    }
    lines.extend([
        "    default:".to_owned(),
        format!(
            "      return err({{ type: 'UnknownCommand' }} as unknown as {}Error)",
            aggregate.name
        ),
        "  }".to_owned(),
        "}".to_owned(),
        String::new(),
    ]);
    lines.join("\n")
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
        && chars.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn render_ts_assignment(assignment: &DomainAssignment) -> Option<String> {
    let target = assignment.target.render_source();
    if !is_identifier(&target) {
        return None;
    }
    let value = assignment.value.render_source();
    let expression = value.trim();
    let expression = if is_identifier(expression) {
        format!("\"{expression}\"")
    } else {
        expression.to_owned()
    };
    Some(format!("{}: {expression}", camel(&target)))
}

fn emit_evolve(aggregate: &DomainAggregate) -> String {
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Keep pure: no I/O, clocks, repositories, or network calls."
            .to_owned(),
        format!(
            "import {{ type {}Event, type {}State }} from '../types'",
            aggregate.name, aggregate.name
        ),
        String::new(),
        format!(
            "export function evolve{}(state: {}State, event: {}Event): {}State {{",
            aggregate.name, aggregate.name, aggregate.name, aggregate.name
        ),
        "  switch (event.type) {".to_owned(),
    ];
    for event in &aggregate.events {
        let evolution = aggregate
            .evolves
            .iter()
            .find(|evolution| evolution.event == event.name);
        lines.push(format!("    case \"{}\":", event.name));
        let Some(evolution) = evolution.filter(|evolution| !evolution.assignments.is_empty())
        else {
            lines.push("      return state".to_owned());
            continue;
        };
        let mut fields = Vec::new();
        for assignment in &evolution.assignments {
            if let Some(rendered) = render_ts_assignment(assignment) {
                fields.push(rendered);
            } else {
                lines.push(format!(
                    "      // {} = {}",
                    assignment.target.render_source(),
                    assignment.value.render_source()
                ));
            }
        }
        lines.push(format!(
            "      return {{ ...state, {} }}",
            fields.join(", ")
        ));
    }
    lines.extend([
        "    default:".to_owned(),
        "      return state".to_owned(),
        "  }".to_owned(),
        "}".to_owned(),
        String::new(),
    ]);
    lines.join("\n")
}

fn action_name(name: &str) -> String {
    let mut output = String::new();
    let chars = name.chars().collect::<Vec<_>>();
    for (index, character) in chars.iter().copied().enumerate() {
        if index > 0 && character.is_ascii_uppercase() {
            let previous = chars[index - 1];
            let next_is_lower = chars.get(index + 1).is_some_and(char::is_ascii_lowercase);
            if previous.is_ascii_lowercase() || previous.is_ascii_digit() || next_is_lower {
                output.push('_');
            }
        }
        output.push(character.to_ascii_lowercase());
    }
    output
}

fn emit_adapter(aggregate: &DomainAggregate) -> String {
    let name = &aggregate.name;
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Wire this adapter to fslc testgen output."
            .to_owned(),
        format!("import {{ decide{name} }} from './decide'"),
        format!("import {{ evolve{name} }} from './evolve'"),
        format!("import {{ type {name}Command, type {name}State }} from '../types'"),
        String::new(),
        format!("export class {name}FslAdapter {{"),
        format!("  private state: {name}State"),
        String::new(),
        format!("  constructor(initialState: {name}State) {{"),
        "    this.state = initialState".to_owned(),
        "  }".to_owned(),
        String::new(),
        format!("  reset(initialState: {name}State): void {{"),
        "    this.state = initialState".to_owned(),
        "  }".to_owned(),
        String::new(),
        "  step(action: string, params: Record<string, unknown>) {".to_owned(),
        "    const command = mapFslActionToCommand(action, params)".to_owned(),
        format!("    const result = decide{name}(this.state, command)"),
        "    if (result.ok) {".to_owned(),
        format!("      this.state = result.value.reduce((s, e) => evolve{name}(s, e), this.state)"),
        "    }".to_owned(),
        "    return result".to_owned(),
        "  }".to_owned(),
        String::new(),
        "  observe() {".to_owned(),
        "    return { ...this.state }".to_owned(),
        "  }".to_owned(),
        "}".to_owned(),
        String::new(),
        format!(
            "export function mapFslActionToCommand(action: string, params: Record<string, unknown>): {name}Command {{"
        ),
        "  switch (action) {".to_owned(),
    ];
    for command in &aggregate.commands {
        lines.extend([
            format!(
                "    case \"{}_{}\":",
                action_name(name),
                action_name(&command.name)
            ),
            format!(
                "      return {{ type: \"{}\", ...(params as any) }} as {name}Command",
                command.name
            ),
        ]);
    }
    lines.extend([
        "    default:".to_owned(),
        "      throw new Error(`Unknown FSL action: ${action}`)".to_owned(),
        "  }".to_owned(),
        "}".to_owned(),
        String::new(),
    ]);
    lines.join("\n")
}

fn all_event_union(domain: &DomainSpec) -> String {
    let union = domain
        .aggregates
        .iter()
        .map(|aggregate| format!("{}Event", aggregate.name))
        .collect::<Vec<_>>()
        .join(" | ");
    if union.is_empty() {
        "never".to_owned()
    } else {
        union
    }
}

fn event_type_for(domain: &DomainSpec, event_name: &str) -> String {
    domain
        .aggregates
        .iter()
        .find(|aggregate| {
            aggregate
                .events
                .iter()
                .any(|event| event.name == event_name)
        })
        .map_or_else(
            || "never".to_owned(),
            |aggregate| {
                format!(
                    "Extract<{}Event, {{ type: \"{event_name}\" }}>",
                    aggregate.name
                )
            },
        )
}

fn emit_effects(domain: &DomainSpec) -> String {
    let imports = domain
        .aggregates
        .iter()
        .map(|aggregate| format!("{}Event", aggregate.name))
        .collect::<Vec<_>>()
        .join(", ");
    let union = all_event_union(domain);
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Effect handlers are outside the pure domain core."
            .to_owned(),
        format!("import type {{ {imports} }} from './types'"),
        String::new(),
    ];
    for effect in &domain.effects {
        let outcomes = effect
            .outcomes
            .iter()
            .map(|event| event_type_for(domain, event))
            .collect::<Vec<_>>()
            .join(" | ");
        let outcomes = if outcomes.is_empty() {
            "never".to_owned()
        } else {
            outcomes
        };
        let request = effect
            .handles
            .as_deref()
            .or(effect.request_event.as_deref())
            .unwrap_or("unknown");
        lines.extend([
            format!("export interface {}Handler {{", effect.name),
            format!(
                "  handle(event: Extract<{union}, {{ type: \"{request}\" }}>): Promise<{outcomes}>"
            ),
            "}".to_owned(),
            String::new(),
        ]);
    }
    lines.join("\n")
}

fn saga_initial_emits(saga: &DomainSaga) -> &[String] {
    saga.steps.first().map_or(&[], |step| step.emits.as_slice())
}

fn event_placeholder(domain: &DomainSpec, event_name: &str) -> String {
    for aggregate in &domain.aggregates {
        if let Some(event) = aggregate
            .events
            .iter()
            .find(|event| event.name == event_name)
        {
            let mut fields = vec![format!("type: \"{}\"", event.name)];
            fields.extend(event.fields.iter().map(|field| {
                format!(
                    "{}: undefined as unknown as {}",
                    camel(&field.name),
                    type_name(&field.type_name)
                )
            }));
            return format!("{{ {} }} as {}Event", fields.join(", "), aggregate.name);
        }
    }
    format!("{{ type: \"{event_name}\" }} as DomainEvent")
}

fn emit_actions(domain: &DomainSpec, events: &[String]) -> String {
    events
        .iter()
        .map(|event| {
            format!(
                "{{ type: \"emit\", event: {} }}",
                event_placeholder(domain, event)
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_process_manager(domain: &DomainSpec) -> String {
    let imports = domain
        .aggregates
        .iter()
        .map(|aggregate| format!("{}Event", aggregate.name))
        .collect::<Vec<_>>()
        .join(", ");
    let mut lines = vec![
        "// Auto-generated by fslc domain generate. Process managers coordinate events; keep side effects in handlers."
            .to_owned(),
        format!("import type {{ {imports} }} from './types'"),
        String::new(),
        format!("type DomainEvent = {}", all_event_union(domain)),
        "type ProcessAction = { type: string; event: DomainEvent }".to_owned(),
        String::new(),
    ];
    for saga in &domain.sagas {
        lines.extend([
            format!(
                "export function on{}(event: DomainEvent): ProcessAction[] {{",
                saga.name
            ),
            "  switch (event.type) {".to_owned(),
        ]);
        if let Some(starts_on) = &saga.starts_on {
            lines.push(format!("    case \"{starts_on}\":"));
            let emitted = saga_initial_emits(saga);
            if emitted.is_empty() {
                lines.push("      return []".to_owned());
            } else {
                lines.push(format!("      return [{}]", emit_actions(domain, emitted)));
            }
        }
        for compensation in &saga.compensations {
            lines.push(format!("    case \"{}\":", compensation.trigger_event));
            if compensation.emits.is_empty() {
                lines.push("      return []".to_owned());
            } else {
                lines.extend([
                    format!("      // after {}", compensation.after_event),
                    format!(
                        "      return [{}]",
                        emit_actions(domain, &compensation.emits)
                    ),
                ]);
            }
        }
        lines.extend([
            "    default:".to_owned(),
            "      return []".to_owned(),
            "  }".to_owned(),
            "}".to_owned(),
            String::new(),
        ]);
    }
    lines.join("\n")
}
