# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ryoichi Izumita

"""Deterministic spec-to-human explanation helpers."""
from __future__ import annotations

import re
from pathlib import Path

from .bmc import _collect_partial_op_sites, _requirement, scenarios
from .model import FslError, build_spec
from .mutate import _apply, _oracle, enumerate_mutants
from .parser import parse_src
from .render import (
    _BIN_PREC,
    _binder_to_text,
    _display_from,
    _expr_prec,
    _render_operand,
    _type_ref_to_text,
    expr_to_text as _expr_to_text,
    public_var as _public_name,
)
from .undecided import undecided_declarations


WEAKENING_OPS = {
    "requires_remove": "requires-removal",
    "assignment_remove": "assignment-removal",
    "fair_remove": "fair-removal",
}

_GENERATED_LABEL = "generated by verifier"
_TRANSITION_ACTOR_RE = re.compile(
    r"\bby\s+(.+?)(?:\s+with\b|\s+when\b|\s+set\b|\s+covers\b|$)"
)


def _public_type(ty):
    if isinstance(ty, tuple):
        return [_public_type(x) for x in ty]
    if isinstance(ty, list):
        return [_public_type(x) for x in ty]
    if isinstance(ty, dict):
        return {k.replace("__", ".") if isinstance(k, str) else k: _public_type(v)
                for k, v in ty.items() if k != "ty"}
    if isinstance(ty, str):
        return ty.replace("__", ".")
    return ty


def _source_line(source_lines, loc):
    if not loc or not source_lines:
        return None
    line = loc.get("line")
    if not line or line < 1 or line > len(source_lines):
        return None
    text = source_lines[line - 1].strip()
    if not text:
        return None
    return text


def _requirement_from_meta(meta):
    if not meta:
        return None
    out = {"id": meta["id"], "text": meta.get("text")}
    if meta.get("controls"):
        out["controls"] = meta["controls"]
    return out


def _actor(action):
    req = _requirement(action)
    text = (req or {}).get("text") or ""
    if text.startswith("by "):
        return text[3:]
    return None


def _lvalue_root(lvalue):
    if not isinstance(lvalue, tuple) or not lvalue:
        return None
    tag = lvalue[0]
    if tag == "var":
        return lvalue[1]
    if tag == "index":
        return lvalue[1]
    if tag == "field_lv":
        return _lvalue_root(lvalue[1])
    return None


def _stmt_writes(stmts, spec):
    writes = set()
    for stmt in stmts:
        if not isinstance(stmt, tuple) or not stmt:
            continue
        if stmt[0] == "assign":
            root = _lvalue_root(stmt[1])
            if root:
                writes.add(_public_name(root, spec))
        elif stmt[0] == "if":
            writes.update(_stmt_writes(stmt[2], spec))
            writes.update(_stmt_writes(stmt[3], spec))
        elif stmt[0] == "forall_stmt":
            writes.update(_stmt_writes(stmt[2], spec))
    return sorted(writes)


def _is_generated_name(name, spec):
    """True for a declaration name synthesized by a dialect frontend (time-tick,
    governance scaffolding, deadline invariants) rather than authored by hand.
    `generated_names` is the frontends' own registry; `_deadline_` is the one
    synthesized-invariant family that isn't (yet) registered there."""
    if not isinstance(name, str):
        return False
    if name in (spec.get("generated_names") or []):
        return True
    return name.startswith("_deadline_")


def _actor_from_source(action, source_lines):
    """Fallback for business-dialect transitions that used `covers REQ-n "..."`
    instead of a bare `by <actor>` meta: the actor name never survives into the
    kernel AST for those, so recover it from the `transition ... by <actor>`
    source line itself (still exact, since one transition = one declaration)."""
    for r in action.get("requires", []):
        text = _source_line(source_lines, r.get("loc"))
        if not text:
            continue
        match = _TRANSITION_ACTOR_RE.search(text)
        if match:
            return " ".join(match.group(1).split())
    return None


def _action_skeleton(action, spec, source_lines):
    label = _public_name(action["name"], spec)
    req = _requirement(action)
    display_names = spec.get("display_names")
    out = {
        "name": label,
        "params": [
            {"name": n, "type": tname.replace("__", "."), "lo": lo, "hi": hi}
            for n, lo, hi, tname in action.get("params", [])
        ],
        "requires_text": [
            f"requires {_expr_to_text(r['expr'], display_names)}"
            for r in action.get("requires", [])
        ],
        "writes": _stmt_writes(action.get("stmts", []), spec),
        "ensures_text": [
            f"ensures {_expr_to_text(e['expr'], display_names)}"
            for e in action.get("ensures", [])
        ],
        "requirement": req,
    }
    actor = _actor(action) or _actor_from_source(action, source_lines)
    if actor:
        out["actor"] = actor
    if action.get("fair"):
        out["fair"] = True
    generated = action.get("generated")
    if generated:
        out["generated"] = generated
    elif _is_generated_name(action["name"], spec):
        out["generated"] = True
    return out


def _leadsto_body_text(item, display_names):
    prefix = "".join(
        f"forall {_binder_to_text(b, display_names)}: " for b in item.get("binders") or []
    )
    text = (
        f"{prefix}{_expr_to_text(item['P'], display_names)} "
        f"~> {_expr_to_text(item['Q'], display_names)}"
    )
    if item.get("within") is not None:
        text += f" within {item['within']}"
    helpful = item.get("helpful") or []
    if helpful:
        helper_text = []
        for helper in helpful:
            args = ", ".join(_expr_to_text(arg, display_names) for arg in helper.get("args") or [])
            helper_text.append(f"helpful {helper['action']}({args})")
        text += "; " + "; ".join(helper_text)
    if item.get("decreases") is not None:
        text += f"; decreases {_expr_to_text(item['decreases'], display_names)}"
    return text


def _property_body_text(kind, item, display_names):
    if kind == "leadsTo":
        return _leadsto_body_text(item, display_names)
    return _expr_to_text(item["expr"], display_names)


def _property_skeleton(kind, item, spec):
    label = _public_name(item["name"], spec)
    display_names = spec.get("display_names")
    out = {
        "kind": kind,
        "name": label,
        "body_text": _property_body_text(kind, item, display_names),
        "requirement": _requirement(item),
    }
    if kind == "leadsTo" and item.get("within") is not None:
        out["within"] = item["within"]
    if _is_generated_name(item["name"], spec):
        out["generated"] = True
    return out


def _auto_checks(spec, source_lines):
    checks = []
    for inv in spec.get("invariants", []):
        if not inv.get("implicit"):
            continue
        checks.append({
            "kind": "type_bound",
            "name": _public_name(inv["name"], spec),
            "target": _public_name(inv.get("logical_var"), spec),
            "requirement": None,
        })
    for action in spec.get("actions", []):
        action_label = _public_name(action["name"], spec)
        for site in _collect_partial_op_sites(action):
            checks.append({
                "kind": "partial_op",
                "name": _public_name(f"_partial_{action['name']}", spec),
                "action": action_label,
                "loc": site.get("loc"),
                "text": _source_line(source_lines, site.get("loc")) or _GENERATED_LABEL,
                "requirement": _requirement(action),
            })
    return checks


def _kpis_skeleton(spec):
    return [
        {
            "name": kpi["name"],
            "entity": kpi["entity"].replace("__", "."),
            "stage": kpi["stage"].replace("__", "."),
        }
        for kpi in sorted(spec.get("kpis") or [], key=lambda k: k["name"])
    ]


def _enums_skeleton(spec):
    out = {}
    for name, info in (spec.get("types") or {}).items():
        if info.get("kind") != "enum":
            continue
        out[name.replace("__", ".")] = [m.replace("__", ".") for m in info.get("members", [])]
    return out


def _enum_value_type(ty):
    """If `ty`'s value position resolves to an enum (directly, or nested in a
    Map/Option/Set), return that enum's (internal) type name."""
    if not isinstance(ty, tuple) or not ty:
        return None
    tag = ty[0]
    if tag == "enum":
        return ty[1]
    if tag == "map":
        return _enum_value_type(ty[2])
    if tag in ("option", "set"):
        return _enum_value_type(ty[1])
    return None


def _reads_state_var(expr, name):
    """True if `expr` is exactly a (possibly indexed) read of state var `name`."""
    if not isinstance(expr, tuple) or not expr:
        return False
    if expr[0] == "var":
        return expr[1] == name
    if expr[0] == "index":
        base = expr[1]
        return isinstance(base, tuple) and base[0] == "var" and base[1] == name
    return False


def _bare_member(expr, members):
    if isinstance(expr, tuple) and len(expr) > 1 and expr[0] == "var" and expr[1] in members:
        return expr[1]
    return None


def _stage_equality(expr, name, members):
    if not isinstance(expr, tuple) or len(expr) < 4 or expr[0] != "bin" or expr[1] != "==":
        return None
    lhs, rhs = expr[2], expr[3]
    if _reads_state_var(lhs, name):
        return _bare_member(rhs, members)
    if _reads_state_var(rhs, name):
        return _bare_member(lhs, members)
    return None


def _stage_assignment(stmts, name, members):
    for stmt in stmts:
        if not isinstance(stmt, tuple) or not stmt or stmt[0] != "assign":
            continue
        if _lvalue_root(stmt[1]) != name:
            continue
        member = _bare_member(stmt[2], members)
        if member:
            return member
    return None


def _stage_flows(spec, source_lines):
    """Reconstruct per-enum-valued-state transition edges (from-stage, to-stage,
    action, actor) straight from the desugared kernel actions' guard-equality +
    assignment shape. This is exactly how the business `process` dialect compiles
    down, but the derivation itself is dialect-agnostic: any hand-written state
    machine over an enum-typed state var is picked up the same way."""
    state = spec.get("state", {})
    types_meta = spec.get("types") or {}
    flows = {}
    members_by_var = {}
    for name, ty in state.items():
        enum_name = _enum_value_type(ty)
        if enum_name is None or enum_name not in types_meta:
            continue
        members = types_meta[enum_name].get("members") or []
        if not members:
            continue
        members_by_var[name] = set(members)
        flows[name] = {
            "state": _public_name(name, spec),
            "type": enum_name.replace("__", "."),
            "stages": [m.replace("__", ".") for m in members],
            "transitions": [],
        }
    if not flows:
        return []
    for action in spec.get("actions", []):
        label = _public_name(action["name"], spec)
        actor = _actor(action) or _actor_from_source(action, source_lines)
        for name, members in members_by_var.items():
            from_stage = None
            for r in action.get("requires", []):
                from_stage = _stage_equality(r["expr"], name, members)
                if from_stage:
                    break
            if from_stage is None:
                continue
            to_stage = _stage_assignment(action.get("stmts", []), name, members)
            if to_stage is None:
                continue
            entry = {
                "action": label,
                "from": from_stage.replace("__", "."),
                "to": to_stage.replace("__", "."),
            }
            if actor:
                entry["actor"] = actor
            flows[name]["transitions"].append(entry)
    return [flow for flow in flows.values() if flow["transitions"]]


def _skeleton(spec, source_lines):
    properties = []
    properties.extend(_property_skeleton("invariant", inv, spec)
                      for inv in spec.get("user_invariants", []))
    properties.extend(_property_skeleton("trans", tr, spec)
                      for tr in spec.get("transitions", []))
    properties.extend(_property_skeleton("leadsTo", lt, spec)
                      for lt in spec.get("leadstos", []))
    properties.extend(_property_skeleton("reachable", reach, spec)
                      for reach in spec.get("reachables", []))
    return {
        # `spec_kind`, not `kind`: the enveloped result tree reserves `kind` for the
        # string diagnostic discriminator that with_faithfulness/trace_type_for scan.
        "spec_kind": spec.get("kind"),
        "state": {
            _public_name(name, spec): _public_type(ty)
            for name, ty in spec.get("state", {}).items()
        },
        "actions": [_action_skeleton(a, spec, source_lines)
                    for a in spec.get("actions", [])],
        "properties": properties,
        "auto_checks": _auto_checks(spec, source_lines),
        "kpis": _kpis_skeleton(spec),
        "domains": _verification_world_lines(spec),
        "enums": _enums_skeleton(spec),
        "stage_flows": _stage_flows(spec, source_lines),
        "undecided": undecided_declarations(spec),
    }


def _state_type_text(name, ty, spec):
    refs = spec.get("state_type_refs") or {}
    if name in refs:
        return _type_ref_to_text(refs[name])
    return _type_ref_to_text(_public_type(ty))


def _map_key_domain_names(ty):
    if isinstance(ty, list):
        ty = tuple(ty)
    if not isinstance(ty, tuple) or not ty:
        return set()
    tag = ty[0]
    if tag == "map":
        out = set()
        key = ty[1]
        if isinstance(key, list):
            key = tuple(key)
        if isinstance(key, tuple) and key and key[0] in ("named", "name"):
            out.add(key[1])
        out.update(_map_key_domain_names(ty[2]))
        return out
    if tag in ("option", "set", "seq"):
        return _map_key_domain_names(ty[1])
    return set()


def _entity_domain_names(spec):
    out = set()
    for ty in (spec.get("state_type_refs") or {}).values():
        out.update(_map_key_domain_names(ty))
    return out


def _verification_world_lines(spec):
    entities = _entity_domain_names(spec)
    lines = []
    for name, info in sorted((spec.get("types") or {}).items()):
        if info.get("kind") != "domain":
            continue
        if name.startswith("_"):
            continue  # generated (e.g. a time-block age type), not domain content
        lo = info.get("lo")
        hi = info.get("hi")
        if lo is None or hi is None:
            continue
        count = hi - lo + 1
        public = name.replace("__", ".")
        if name in entities:
            lines.append(f"{public}: {count} instances ({lo}..{hi})")
        else:
            lines.append(f"{public}: values {lo}..{hi} ({count} values)")
    return lines


def _params_text(params, include_types=True):
    rendered = []
    for param in params or []:
        if isinstance(param, dict):
            name = param.get("name")
            ty = param.get("type")
        elif isinstance(param, tuple) and param and param[0] == "refinement_param":
            name = param[1]
            ty = _type_ref_to_text(param[2]) if param[2] is not None else None
        else:
            name = str(param)
            ty = None
        if include_types and ty:
            rendered.append(f"{name}: {ty}")
        else:
            rendered.append(str(name))
    return ", ".join(rendered)


def _requirement_text(req):
    if not req:
        return None
    rid = req.get("id")
    text = req.get("text")
    if rid and text:
        return f"{{{rid}: {text}}}"
    if rid:
        return f"{{{rid}}}"
    if text:
        return f"{{{text}}}"
    return None


def _dedupe(items):
    out = []
    seen = set()
    for item in items or []:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def _actor_from_action(action):
    if action.get("actor"):
        return action["actor"]
    for text in action.get("requires_text") or []:
        match = _TRANSITION_ACTOR_RE.search(text)
        if match:
            return " ".join(match.group(1).split())
    return None


def _binder_name(binder):
    if isinstance(binder, tuple) and len(binder) > 1:
        return binder[1]
    return "?"


def _branch_lowering_lines(display_names):
    groups = {}
    for _physical, label in sorted((display_names or {}).items()):
        if not isinstance(label, str) or "[" not in label or not label.endswith("]"):
            continue
        base = label.split("[", 1)[0]
        groups.setdefault(base, []).append(label)
    return [
        f"{base} \u2192 {', '.join(labels)}"
        for base, labels in sorted(groups.items())
    ]


def _mapping_state_line(item, impl_display_names, abs_display_names):
    _, logical, binder, expr, _loc = item
    lhs = _display_from(abs_display_names, logical)
    if binder is not None:
        lhs = f"{lhs}[{_binder_name(binder)}]"
    return f"{lhs} \u21a6 {_expr_to_text(expr, impl_display_names)}"


def _mapping_action_line(item, impl_display_names, abs_display_names):
    _, aname, params, target, _loc = item
    lhs = _display_from(impl_display_names, aname)
    lhs = f"{lhs}({_params_text(params, include_types=False)})"
    if target[0] == "stutter":
        rhs = "stutter"
    else:
        _, abs_name, args = target
        rhs = _display_from(abs_display_names, abs_name)
        rhs = f"{rhs}({', '.join(_expr_to_text(arg, impl_display_names) for arg in args)})"
    return f"{lhs} \u21a6 {rhs}"


def _refinement_mapping_lines(spec, display_names):
    impl = spec.get("implements")
    if not impl or not impl.get("mapping_ast"):
        return []
    impl_display_names = spec.get("display_names") or display_names or {}
    abs_display_names = impl.get("abs_display_names") or {}
    lines = [
        f"  - implements {spec['name']} \u21a6 {impl.get('abs')}",
        "    includes explicit maps and generated-by-name correspondences; review actor/intent matches",
    ]
    state_lines = []
    action_lines = []
    for item in impl["mapping_ast"][2]:
        if item[0] == "map":
            state_lines.append(_mapping_state_line(item, impl_display_names, abs_display_names))
        elif item[0] == "action_map":
            action_lines.append(_mapping_action_line(item, impl_display_names, abs_display_names))
    if state_lines:
        lines.append("    state maps:")
        lines.extend(f"      - {line}" for line in state_lines)
    if action_lines:
        lines.append("    action correspondences:")
        lines.extend(f"      - {line}" for line in action_lines)
    return lines


def render_readable(explained: dict, spec: dict, display_names: dict) -> str:
    """Render an explain result as deterministic human-readable text."""
    skeleton = explained.get("skeleton") or {}
    lines = [f"Spec: {spec['name']} (depth {explained.get('depth')})"]
    kind = spec.get("kind")
    if kind:
        tag = kind["id"] if kind.get("text") is None else f"{kind['id']}: {kind['text']}"
        lines.append(f"Kind: {tag}")

    def section(title, items):
        if not items:
            return
        lines.append("")
        lines.append(f"{title}:")
        lines.extend(items)

    section("Verification world", [f"  - {line}" for line in _verification_world_lines(spec)])

    state_items = []
    state_order = sorted(
        spec.get("state", {}),
        key=lambda internal: _public_name(internal, spec),
    )
    for internal in state_order:
        name = _public_name(internal, spec)
        state_items.append(f"  - {name}: {_state_type_text(internal, spec['state'][internal], spec)}")
    section("State", state_items)

    action_items = []
    generated_by_name = {
        _public_name(action["name"], spec): action.get("generated")
        for action in spec.get("actions", [])
    }
    for action in skeleton.get("actions") or []:
        params = _params_text(action.get("params"))
        generated = generated_by_name.get(action["name"])
        marker = []
        if action.get("fair"):
            marker.append("fair")
        if generated and generated.get("kind") == "time_tick":
            marker.append("generated by time block")
        elif action["name"] == "tick" and generated is not None:
            marker.append("generated")
        suffix = f" [{' | '.join(marker)}]" if marker else ""
        actor = _actor_from_action(action)
        actor_text = f" actor: {actor}" if actor else ""
        action_items.append(f"  - {action['name']}({params}){suffix}{actor_text}")
        req = _requirement_text(action.get("requirement"))
        if req:
            action_items.append(f"    requirement: {req}")
        requires = _dedupe(action.get("requires_text"))
        if requires:
            action_items.append("    requires:")
            action_items.extend(f"      - {text}" for text in requires)
        writes = action.get("writes") or []
        if writes:
            action_items.append(f"    writes: {', '.join(writes)}")
    section("Actions", action_items)

    kpi_items = [
        (
            f"  - {kpi['name']} = count of {kpi['entity']} in {kpi['stage']} "
            "(derived projection - not stored state)"
        )
        for kpi in sorted(spec.get("kpis") or [], key=lambda item: item["name"])
    ]
    section("Derived metrics (KPIs)", kpi_items)

    prop_items = []
    for prop in skeleton.get("properties") or []:
        req = _requirement_text(prop.get("requirement"))
        req_text = f" {req}" if req else ""
        within = f" [within {prop['within']}]" if prop.get("within") is not None else ""
        prop_items.append(f"  - {prop['kind']} {prop['name']}{within}{req_text}")
        if prop.get("body_text"):
            prop_items.append(f"    body: {prop['body_text']}")
    section("Properties", prop_items)

    check_items = []
    for check in skeleton.get("auto_checks") or []:
        if check.get("kind") == "type_bound":
            check_items.append(
                f"  - type_bound: {check.get('target')} (implicit bounded-domain check)"
            )
        elif check.get("kind") == "partial_op":
            check_items.append(
                f"  - partial_op: {check.get('action')} checks {check.get('text')}"
            )
        else:
            check_items.append(f"  - {check.get('kind')}: {check.get('name')}")
    section("Automatic checks", check_items)

    branch_items = [f"  - {line}" for line in _branch_lowering_lines(spec.get("display_names") or display_names)]
    section("Branch lowering", branch_items)

    section("Refinement mapping (synthesized + explicit)", _refinement_mapping_lines(spec, display_names))

    fair = [action["name"] for action in skeleton.get("actions") or [] if action.get("fair")]
    section("Fairness assumptions", [f"  - fair: {', '.join(fair)}"] if fair else [])

    return "\n".join(lines)


def _trace_len(result):
    trace = result.get("trace") or []
    return len(trace)


def _weakening(mutant, source_lines):
    out = {
        "op": WEAKENING_OPS.get(mutant.op, mutant.op.replace("_", "-")),
        "loc": mutant.loc,
        "target": mutant.target.replace("__", ".") if isinstance(mutant.target, str) else mutant.target,
        "source_text": _source_line(source_lines, mutant.loc),
    }
    if mutant.action == "init":
        out["origin"] = "init"
        out["label"] = "init weakening"
    return out


def _counterfactuals(ast, display_names, spec, source_lines, depth, max_mutants):
    _, name, items = ast
    invariant_labels = {
        _public_name(inv["name"], spec): inv for inv in spec.get("user_invariants", [])
    }
    found = {}
    reachable_kills = []
    op_priority = {"assignment_remove": 0, "requires_remove": 1, "fair_remove": 2}

    processed = 0
    for mutant in enumerate_mutants(ast, display_names):
        if mutant.op not in WEAKENING_OPS:
            continue
        if max_mutants is not None and processed >= max_mutants:
            break
        processed += 1
        try:
            mutated_spec = build_spec(("spec", name, _apply(items, mutant)), display_names)
            oracle = _oracle(mutated_spec, depth, source_lines=source_lines)
        except FslError:
            continue
        if oracle.get("clean"):
            continue
        result = oracle.get("result") or {}
        killed_by = oracle.get("killed_by")
        if killed_by in invariant_labels:
            current = found.get(killed_by)
            candidate_key = (
                _trace_len(result),
                op_priority.get(mutant.op, 99),
                (mutant.loc or {}).get("line") or 10**9,
            )
            if current is None or candidate_key < current["_key"]:
                found[killed_by] = {
                    "_key": candidate_key,
                    "invariant": killed_by,
                    "weakening": _weakening(mutant, source_lines),
                    "trace": result.get("trace"),
                    "requirement": _requirement(invariant_labels[killed_by]),
                    "violation": {
                        k: v for k, v in result.items()
                        if k not in ("trace", "spec", "result")
                    },
                }
        elif result.get("result") == "reachable_failed":
            reachable_kills.append({
                "property": killed_by,
                "weakening": _weakening(mutant, source_lines),
                "result": "reachable_failed",
                "requirement": oracle.get("killer_requirement"),
            })

    out = []
    for inv_label, inv in invariant_labels.items():
        if inv_label in found:
            item = dict(found[inv_label])
            item.pop("_key", None)
            out.append(item)
        else:
            out.append({
                "invariant": inv_label,
                "weakening": None,
                "trace": None,
                "requirement": _requirement(inv),
                "note": f"no counterfactual within depth {depth}",
            })
    return out, reachable_kills


def _narrate_steps(steps):
    lines = []
    for idx, step in enumerate(steps or [], start=1):
        action = step.get("action")
        params = step.get("params") or {}
        rendered = ", ".join(f"{k}={v}" for k, v in params.items())
        lines.append(f"{idx}. {action}({rendered})" if rendered else f"{idx}. {action}()")
    return lines


def _witnesses(spec, source_lines, depth):
    result = scenarios(spec, depth, deadlock_mode="warn", source_lines=source_lines)
    if result.get("result") != "scenarios":
        return []
    reqs = {}
    for item in spec.get("reachables", []) + spec.get("leadstos", []):
        reqs[_public_name(item["name"], spec)] = _requirement(item)
    for action in spec.get("actions", []):
        reqs[_public_name(action["name"], spec)] = _requirement(action)
    for item in spec.get("acceptance", []) + spec.get("forbidden", []):
        reqs[item["id"]] = {"id": item["id"], "text": item.get("text")}
    witnesses = []
    for scenario in result.get("scenarios", []):
        keys = [
            scenario.get("property"),
            scenario.get("action"),
            scenario.get("final_check"),
            scenario.get("acceptance"),
            scenario.get("forbidden"),
        ]
        key = next((k for k in keys if k), None)
        requirement = scenario.get("requirement")
        if requirement is None:
            requirement = next((reqs[k] for k in keys if k in reqs), None)
        witnesses.append({
            "name": scenario.get("name"),
            "kind": scenario.get("kind"),
            "target": key,
            "requirement": requirement,
            "steps": scenario.get("steps", []),
            "narration": _narrate_steps(scenario.get("steps", [])),
            "initial_state": scenario.get("initial_state"),
            "expected_states": scenario.get("expected_states", []),
        })
    return witnesses


def explain_file(file, depth=8, max_mutants=None, readable=False):
    src = Path(file).read_text(encoding="utf-8")
    ast, display_names = parse_src(src, str(Path(file).parent))
    if ast[0] != "spec":
        raise FslError("explain expects a spec-like FSL file", kind="semantics")
    source_lines = src.splitlines()
    spec = build_spec(ast, display_names)
    out = {
        "result": "explained",
        "spec": spec["name"],
        "depth": depth,
        "skeleton": _skeleton(spec, source_lines),
    }
    if readable:
        out["readable"] = render_readable(out, spec, display_names)
        return out
    counterfactuals, reachable_kills = _counterfactuals(
        ast, display_names, spec, source_lines, depth, max_mutants
    )
    out["counterfactuals"] = counterfactuals
    out["witnesses"] = _witnesses(spec, source_lines, depth)
    if reachable_kills:
        out["reachable_counterfactuals"] = reachable_kills
    return out
